baseURL = "https://nilbrahim.github.io/website2026/"
title = "Niloofar Ebrahimi"
theme = "PaperMod"

[params]
assets = { customCSS = ["css/custom.css"] }
mainSections = []

[pagination]
pagerSize = 10
  
[markup.goldmark.renderer]
unsafe = true
  
[menu]
  

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 1


[[menu.main]]
name = "Reading List"
url = "/reading-list/"
weight = 2

[[menu.main]]
name = "Resources"
url = "/resources/"
weight = 3

[[menu.main]]
name = "CV"
url = "/cv.pdf"
weight = 4
